fix: broken imports in esm + typescript <5.5 (#11)
`import * as ts from "typescript"` does not work as expected in ESM
until TypeScript 5.5 (see
https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#easier-api-consumption-from-ecmascript-modules).
This was causing projects using an ESM eslint config with TypeScript 4.7
through 5.4 to get:

```
Oops! Something went wrong! :(

ESLint: 8.57.1

TypeError: Cannot read properties of undefined (reading 'Any')
```

This changes to `import ts from "typescript"` so the import works on
those older TypeScript versions in ESM.

- Also increase minimum TypeScript version to 4.7.4 to align with
`typescript-eslint/typescript-estree`'s supported versions.